### ISSUE TITLE
require "inotify" problem

### ISSUE THREAD

**Issue by Sam-Dowling** [nisseblink/blink_record#2]
I'm running fedora 21,
I installed ruby and "gem install inotify"
Then installed blink with the graphical installer.

when I try to run blink_record it would give the following error:

```
/usr/share/ruby/fiddle.rb:37:in `initialize': /lib/libc.so.6: wrong ELF class: ELFCLASS32 (Fiddle::DLError)
    from /usr/share/ruby/fiddle.rb:37:in `new'
    from /usr/share/ruby/fiddle.rb:37:in `dlopen'
    from /usr/local/share/gems/gems/inotify-1.0.2/lib/inotify.rb:78:in `<module:InotifyCtypes>'
    from /usr/local/share/gems/gems/inotify-1.0.2/lib/inotify.rb:76:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:144:in `require'
    from /usr/local/bin/blink_record:6:in `<main>'
```

**Comment by nisseblink** [comment]
Sorry for the late response.

Fixed your paste in comment. https://guides.github.com/features/mastering-markdown/ is a good reference for future usage ;)

You should install the gem `ruby-inotify` i.e. `gem install ruby-inotify`
It also seems like you must uninstall the inotify gem i.e. `gem uninstall inotify`

If this does not work:
It seems like something is wrong with your ruby environment. `/lib/libc.so.6: wrong ELF class: ELFCLASS32` tells us that ruby is trying to load an 32 bit into a 64 bit environment. Could you try to it in a different ruby environment? Easiest way imo is using rvm (http://rvm.io/). You don't need to reinstall blink_recorder, only the ruby-inotify gem.

Cheers!
